"""
Django settings for web_ui project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
import shutil
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

# Загрузка .env до чтения os.getenv (для POSTGRES_*, CELERY_* и т.д.)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    raw = (os.getenv(name, "") or "").strip()
    if not raw:
        return list(default or [])
    return [item.strip() for item in raw.split(",") if item.strip()]


def _env_int(name: str, default: int = 0) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    return int(raw.strip())


def _append_unique(values: list[str], *items: str) -> list[str]:
    for item in items:
        value = (item or "").strip()
        if value and value not in values:
            values.append(value)
    return values


def _origin_from_url(value: str) -> str:
    raw = (value or "").strip().rstrip("/")
    if not raw or "://" not in raw:
        return ""
    parsed = urlparse(raw)
    if not parsed.scheme or not parsed.netloc:
        return ""
    return f"{parsed.scheme}://{parsed.netloc}"


def _hostname_from_value(value: str) -> str:
    raw = (value or "").strip()
    if not raw:
        return ""
    parsed = urlparse(raw if "://" in raw else f"http://{raw}")
    return (parsed.hostname or "").strip()


_RENDER_EXTERNAL_URL = (os.getenv("RENDER_EXTERNAL_URL", "") or "").rstrip("/")
_RENDER_EXTERNAL_HOSTNAME = (os.getenv("RENDER_EXTERNAL_HOSTNAME", "") or "").strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", _env_bool("DEBUG", True))

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_SECRET_KEY_FALLBACK = "django-insecure-@b9idj_4skbcph+21q6^bc0qbs*$qs&@7r2sqfn*1#)z5_i%my"
SECRET_KEY = (os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _DEV_SECRET_KEY_FALLBACK
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY or SECRET_KEY must be set when DJANGO_DEBUG=false."
        )
if not DEBUG and (
    SECRET_KEY.startswith("django-insecure-")
    or len(SECRET_KEY) < 50
    or len(set(SECRET_KEY)) < 5
):
    raise ImproperlyConfigured(
        "Set a long random DJANGO_SECRET_KEY for production."
    )

SITE_URL = (
    os.getenv("SITE_URL")
    or _RENDER_EXTERNAL_URL
    or ("http://localhost:9000" if DEBUG else "")
).strip().rstrip("/")

FRONTEND_APP_URL = (
    os.getenv(
        "FRONTEND_APP_URL",
        "http://127.0.0.1:8080" if DEBUG and not _RENDER_EXTERNAL_URL else "",
    )
    or ""
).strip().rstrip("/")

_SITE_ORIGIN = _origin_from_url(SITE_URL)
_FRONTEND_ORIGIN = _origin_from_url(FRONTEND_APP_URL)
_RENDER_ORIGIN = _origin_from_url(_RENDER_EXTERNAL_URL)
_PRODUCTION_HTTPS = (not DEBUG) and any(
    origin.startswith("https://")
    for origin in (_SITE_ORIGIN, _FRONTEND_ORIGIN, _RENDER_ORIGIN)
)

# Р”РѕРјРµРЅ Рё IP СЃРµСЂРІРµСЂР° вЂ” РїРѕ СѓРјРѕР»С‡Р°РЅРёСЋ, С‡С‚РѕР±С‹ СЂР°Р±РѕС‚Р°Р»Рѕ РїРѕ weuai.site Рё РїРѕ IP
_DEFAULT_ALLOWED = [
    "localhost",
    "127.0.0.1",
    "weuai.site",
    "www.weuai.site",
    "188.137.241.228",
    "8c56-46-42-238-129.ngrok-free.app",
    ".ngrok-free.app",  # любой поддомен ngrok (смена URL при рестарте)
]

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")
_append_unique(
    ALLOWED_HOSTS,
    _RENDER_EXTERNAL_HOSTNAME,
    _hostname_from_value(SITE_URL),
    _hostname_from_value(FRONTEND_APP_URL),
    _hostname_from_value(_RENDER_EXTERNAL_URL),
)
if DEBUG:
    _append_unique(ALLOWED_HOSTS, *_DEFAULT_ALLOWED)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be set explicitly or derivable from SITE_URL/FRONTEND_APP_URL in production."
    )

# Dev: разрешаем Origin от Vite dev-сервера (:8080) для WebSocket через прокси
_default_frontend_origins = [
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://127.0.0.1:8081",
    "http://localhost:8081",
]

# Истоки для CSRF. Ngrok-домены добавляются автоматически в core_ui.middleware.CsrfTrustNgrokMiddleware.
# Через .env можно добавить свои: CSRF_TRUSTED_ORIGINS=https://example.com,http://example.com
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")
_append_unique(CSRF_TRUSTED_ORIGINS, _FRONTEND_ORIGIN, _SITE_ORIGIN, _RENDER_ORIGIN)
if DEBUG:
    _append_unique(CSRF_TRUSTED_ORIGINS, *_default_frontend_origins)

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    ([_FRONTEND_ORIGIN] if _FRONTEND_ORIGIN else []),
)
CORS_ALLOW_CREDENTIALS = bool(CORS_ALLOWED_ORIGINS)
if DEBUG:
    _append_unique(CORS_ALLOWED_ORIGINS, *_default_frontend_origins)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'corsheaders',
    'core_ui',
    'servers',
    'studio',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'core_ui.middleware.CsrfTrustNgrokMiddleware',  # до CSRF: доверяет ngrok-домены
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core_ui.domain_auth.DomainAutoLoginMiddleware',
    'core_ui.middleware.RequestAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core_ui.middleware.AdminRussianMiddleware',
    'core_ui.middleware.MobileDetectionMiddleware',
]

ROOT_URLCONF = 'web_ui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core_ui' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core_ui.context_processors.app_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_ui.wsgi.application'
ASGI_APPLICATION = 'web_ui.asgi.application'

# =============================================================================
# Channels (WebSocket) Configuration
# =============================================================================
# In dev we default to in-memory channels layer (no Redis required).
# For production / multi-worker setups set CHANNEL_REDIS_URL, e.g. redis://localhost:6379/1
CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", "").strip()
if not CHANNEL_REDIS_URL and not DEBUG:
    # In production it's reasonable to reuse the same Redis as Celery (if configured)
    CHANNEL_REDIS_URL = os.getenv("CELERY_BROKER_URL", "").strip()

if not DEBUG and not CHANNEL_REDIS_URL:
    raise ImproperlyConfigured(
        "CHANNEL_REDIS_URL (or CELERY_BROKER_URL) must be set when DJANGO_DEBUG=false. "
        "InMemoryChannelLayer is not supported for production or multi-worker runtime control."
    )

if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [CHANNEL_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# MVP: PostgreSQL РґР»СЏ РєРѕРЅРєСѓСЂРµРЅС‚РЅРѕР№ СЂР°Р±РѕС‚С‹ (РјРЅРѕРіРѕ Р°РіРµРЅС‚РѕРІ/РІРѕСЂРєРµСЂРѕРІ Р±РµР· Р±Р»РѕРєРёСЂРѕРІРѕРє SQLite).
# Р—Р°РґР°Р№С‚Рµ POSTGRES_HOST (РёР»Рё POSTGRES_DB) РІ .env вЂ” Р±СѓРґРµС‚ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊСЃСЏ PostgreSQL.
# РРЅР°С‡Рµ вЂ” SQLite РґР»СЏ Р»РѕРєР°Р»СЊРЅРѕРіРѕ СЃС‚Р°СЂС‚Р° Р±РµР· Docker.

def _get_database_config():
    use_postgres = os.getenv("POSTGRES_HOST") or os.getenv("POSTGRES_DB")
    if use_postgres:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "weu_platform"),
            "USER": os.getenv("POSTGRES_USER", "weu"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 0,  # постоянные соединения — БД не закрывается при множестве запросов
            "OPTIONS": {
                "connect_timeout": 10,
                "options": "-c statement_timeout=30000",  # 30s РјР°РєСЃ. РЅР° Р·Р°РїСЂРѕСЃ
            },
        }
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 60,  # ждать lock до 60 сек (polling + логи = много конкурентных запросов)
        },
    }


DATABASES = {"default": _get_database_config()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'servers:server_list'
LOGOUT_REDIRECT_URL = 'login'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

# External SPA frontend (React/Vite)
SERVE_STATIC_FILES = _env_bool("SERVE_STATIC_FILES", not DEBUG)
USE_X_FORWARDED_HOST = _env_bool("USE_X_FORWARDED_HOST", True)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if _env_bool("TRUST_X_FORWARDED_PROTO", True)
    else None
)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", _PRODUCTION_HTTPS)
SECURE_HSTS_SECONDS = _env_int(
    "SECURE_HSTS_SECONDS",
    31536000 if SECURE_SSL_REDIRECT else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    SECURE_HSTS_SECONDS > 0,
)
SECURE_HSTS_PRELOAD = _env_bool(
    "SECURE_HSTS_PRELOAD",
    SECURE_HSTS_SECONDS > 0 and SECURE_HSTS_INCLUDE_SUBDOMAINS,
)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = (
    os.getenv("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
    or "strict-origin-when-cross-origin"
).strip()
SECURE_CROSS_ORIGIN_OPENER_POLICY = (
    os.getenv("SECURE_CROSS_ORIGIN_OPENER_POLICY", "same-origin")
    or "same-origin"
).strip()

_cross_site_auth = _env_bool("CROSS_SITE_AUTH", CORS_ALLOW_CREDENTIALS and not DEBUG)
if _cross_site_auth:
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
    CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)


def _ldap_server_uri() -> str:
    raw = (os.getenv("LDAP_SERVER", "") or "").strip()
    if not raw:
        return ""
    if "://" not in raw:
        raw = f"ldap://{raw}"

    parsed = urlparse(raw)
    configured_port = (os.getenv("LDAP_PORT", "") or "").strip()
    if not configured_port:
        return raw
    if parsed.port:
        return raw

    host = parsed.hostname or parsed.netloc or parsed.path
    if not host:
        return raw
    return f"{parsed.scheme or 'ldap'}://{host}:{configured_port}"


# Domain SSO / integrated auth
# DOMAIN_AUTH_HEADER examples: REMOTE_USER, X-Forwarded-User
DOMAIN_AUTH_ENABLED = _env_bool("DOMAIN_AUTH_ENABLED", False)
DOMAIN_AUTH_HEADER = (os.getenv("DOMAIN_AUTH_HEADER", "REMOTE_USER") or "REMOTE_USER").strip() or "REMOTE_USER"
DOMAIN_AUTH_HEADER_ALIASES = [
    header.strip()
    for header in (
        os.getenv(
            "DOMAIN_AUTH_HEADER_ALIASES",
            "X-Remote-User,Remote-User,X-Auth-Request-User,X-Forwarded-Preferred-Username",
        )
        or ""
    ).split(",")
    if header.strip()
]
DOMAIN_AUTH_AUTO_CREATE = _env_bool("DOMAIN_AUTH_AUTO_CREATE", True)
DOMAIN_AUTH_LOWERCASE_USERNAMES = _env_bool("DOMAIN_AUTH_LOWERCASE_USERNAMES", True)
DOMAIN_AUTH_DEFAULT_PROFILE = (
    os.getenv("DOMAIN_AUTH_DEFAULT_PROFILE", "server_only") or "server_only"
).strip().lower() or "server_only"

# LDAP / AD auth (form-based login against corporate directory)
LDAP_ENABLED = _env_bool("LDAP_ENABLED", False)
LDAP_SERVER = _ldap_server_uri()
LDAP_BIND_DN = (os.getenv("LDAP_BIND_DN", "") or "").strip()
LDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD", "")
LDAP_SEARCH_BASE = (os.getenv("LDAP_SEARCH_BASE", "") or "").strip()
LDAP_FILTER = (os.getenv("LDAP_FILTER", "(objectClass=user)") or "(objectClass=user)").strip()
LDAP_USERNAME_ATTRIBUTE = (os.getenv("LDAP_USERNAME_ATTRIBUTE", "sAMAccountName") or "sAMAccountName").strip()
LDAP_EMAIL_ATTRIBUTE = (os.getenv("LDAP_EMAIL_ATTRIBUTE", "mail") or "mail").strip()
LDAP_FULL_NAME_ATTRIBUTE = (os.getenv("LDAP_FULL_NAME_ATTRIBUTE", "cn") or "cn").strip()
LDAP_START_TLS = _env_bool("LDAP_START_TLS", False)
LDAP_IGNORE_CERT = _env_bool("LDAP_IGNORE_CERT", False)
LDAP_NETWORK_TIMEOUT_SECONDS = int((os.getenv("LDAP_NETWORK_TIMEOUT_SECONDS", "3") or "3").strip() or "3")

if LDAP_ENABLED:
    try:
        import ldap
        from django_auth_ldap.config import LDAPSearch
    except Exception:
        # LDAP package not available -> keep local DB auth only.
        pass
    else:
        AUTHENTICATION_BACKENDS = [
            "django.contrib.auth.backends.ModelBackend",
            "django_auth_ldap.backend.LDAPBackend",
        ]

        AUTH_LDAP_SERVER_URI = LDAP_SERVER
        AUTH_LDAP_BIND_DN = LDAP_BIND_DN
        AUTH_LDAP_BIND_PASSWORD = LDAP_BIND_PASSWORD
        AUTH_LDAP_START_TLS = LDAP_START_TLS
        AUTH_LDAP_ALWAYS_UPDATE_USER = True
        AUTH_LDAP_CACHE_TIMEOUT = 300

        _ldap_username_filter = f"(&{LDAP_FILTER}({LDAP_USERNAME_ATTRIBUTE}=%(user)s))"
        AUTH_LDAP_USER_SEARCH = LDAPSearch(LDAP_SEARCH_BASE, ldap.SCOPE_SUBTREE, _ldap_username_filter)
        AUTH_LDAP_USER_ATTR_MAP = {
            "email": LDAP_EMAIL_ATTRIBUTE,
            "first_name": LDAP_FULL_NAME_ATTRIBUTE,
        }

        AUTH_LDAP_CONNECTION_OPTIONS = {
            ldap.OPT_REFERRALS: 0,
            ldap.OPT_NETWORK_TIMEOUT: LDAP_NETWORK_TIMEOUT_SECONDS,
            ldap.OPT_TIMEOUT: LDAP_NETWORK_TIMEOUT_SECONDS,
        }
        AUTH_LDAP_GLOBAL_OPTIONS = {
            ldap.OPT_REFERRALS: 0,
        }
        if LDAP_IGNORE_CERT:
            AUTH_LDAP_GLOBAL_OPTIONS[ldap.OPT_X_TLS_REQUIRE_CERT] = ldap.OPT_X_TLS_NEVER

# =============================================================================
# Email Configuration
# =============================================================================
# SMTP settings for sending emails (invitations, notifications, etc.)
# For development, use console backend. For production, configure SMTP.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'WEU Platform <noreply@weuai.site>')

# Site URL for email links and approval callbacks
SITE_URL = SITE_URL or (_RENDER_EXTERNAL_URL or "http://localhost:9000")

# =============================================================================
# Pipeline Notifications — global defaults (used when nodes don't override)
# =============================================================================
# Who receives pipeline notifications (approvals, reports, alerts)
PIPELINE_NOTIFY_EMAIL = os.getenv('PIPELINE_NOTIFY_EMAIL', EMAIL_HOST_USER)

# Telegram Bot — used by output/telegram and logic/human_approval nodes globally
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'core_ui' / 'static',
]

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
UPLOADED_FILES_DIR = MEDIA_ROOT / 'uploads'

# Create upload directory if it doesn't exist
UPLOADED_FILES_DIR.mkdir(parents=True, exist_ok=True)

# Agent projects directory
AGENT_PROJECTS_DIR = BASE_DIR / 'agent_projects'
AGENT_PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# CLI runtime timeout (РѕР±С‰РёР№ Р»РёРјРёС‚ РІСЂРµРјРµРЅРё СЂР°Р±РѕС‚С‹ РїСЂРѕС†РµСЃСЃР°)
CLI_RUNTIME_TIMEOUT_SECONDS = int(os.getenv("CLI_RUNTIME_TIMEOUT_SECONDS", "600"))

# РўР°Р№РјР°СѓС‚ В«РїРµСЂРІРѕРіРѕ РІС‹РІРѕРґР°В»: РµСЃР»Рё Claude РЅРµ РІС‹РІРµР» РЅРё РѕРґРЅРѕР№ СЃС‚СЂРѕРєРё Р·Р° СЌС‚Рѕ РІСЂРµРјСЏ вЂ” РїСЂРµСЂРІР°С‚СЊ.
# РћР±С‹С‡РЅРѕ РѕР·РЅР°С‡Р°РµС‚, С‡С‚Рѕ Claude Р¶РґС‘С‚ MCP-СЃРµСЂРІРµСЂ, РєРѕС‚РѕСЂС‹Р№ РЅРµ Р·Р°РїСѓСЃС‚РёР»СЃСЏ РёР»Рё Р·Р°РІРёСЃ РїСЂРё СЃС‚Р°СЂС‚Рµ Django.
CLI_FIRST_OUTPUT_TIMEOUT_SECONDS = int(os.getenv("CLI_FIRST_OUTPUT_TIMEOUT_SECONDS", "120"))

# Runtime concurrency guards. Set any limit to 0 to disable it explicitly.
AGENT_ACTIVE_RUNS_PER_USER_LIMIT = _env_int("AGENT_ACTIVE_RUNS_PER_USER_LIMIT", 5)
AGENT_ACTIVE_RUNS_GLOBAL_LIMIT = _env_int("AGENT_ACTIVE_RUNS_GLOBAL_LIMIT", 25)
PIPELINE_ACTIVE_RUNS_PER_USER_LIMIT = _env_int("PIPELINE_ACTIVE_RUNS_PER_USER_LIMIT", 8)
PIPELINE_ACTIVE_RUNS_GLOBAL_LIMIT = _env_int("PIPELINE_ACTIVE_RUNS_GLOBAL_LIMIT", 40)
SSH_TERMINAL_SESSIONS_PER_USER_LIMIT = _env_int("SSH_TERMINAL_SESSIONS_PER_USER_LIMIT", 12)
SSH_TERMINAL_SESSIONS_GLOBAL_LIMIT = _env_int("SSH_TERMINAL_SESSIONS_GLOBAL_LIMIT", 120)

# Shared SSH transport defaults across terminal, tools, monitor and pipeline SSH execution.
SSH_CONNECT_TIMEOUT_SECONDS = _env_int("SSH_CONNECT_TIMEOUT_SECONDS", 10)
SSH_LOGIN_TIMEOUT_SECONDS = _env_int("SSH_LOGIN_TIMEOUT_SECONDS", 20)
SSH_KEEPALIVE_INTERVAL_SECONDS = _env_int("SSH_KEEPALIVE_INTERVAL_SECONDS", 20)
SSH_KEEPALIVE_COUNT_MAX = _env_int("SSH_KEEPALIVE_COUNT_MAX", 3)

# MCP transport timeouts and safe retries.
MCP_STDIO_INITIALIZE_TIMEOUT_SECONDS = _env_int("MCP_STDIO_INITIALIZE_TIMEOUT_SECONDS", 20)
MCP_STDIO_REQUEST_TIMEOUT_SECONDS = _env_int("MCP_STDIO_REQUEST_TIMEOUT_SECONDS", 30)
MCP_STDIO_TOOL_CALL_TIMEOUT_SECONDS = _env_int("MCP_STDIO_TOOL_CALL_TIMEOUT_SECONDS", 120)
MCP_PROCESS_TERMINATE_TIMEOUT_SECONDS = _env_int("MCP_PROCESS_TERMINATE_TIMEOUT_SECONDS", 2)
MCP_HTTP_CONNECT_TIMEOUT_SECONDS = _env_int("MCP_HTTP_CONNECT_TIMEOUT_SECONDS", 10)
MCP_HTTP_REQUEST_TIMEOUT_SECONDS = _env_int("MCP_HTTP_REQUEST_TIMEOUT_SECONDS", 30)
MCP_HTTP_TOOL_CALL_TIMEOUT_SECONDS = _env_int("MCP_HTTP_TOOL_CALL_TIMEOUT_SECONDS", 120)
MCP_HTTP_RETRY_ATTEMPTS = _env_int("MCP_HTTP_RETRY_ATTEMPTS", 2)

# Shared LLM stream/runtime protection defaults so slow providers fail predictably instead of hanging forever.
LLM_MAX_RETRY_ATTEMPTS = _env_int("LLM_MAX_RETRY_ATTEMPTS", 3)
LLM_PROVIDER_TIMEOUT_SECONDS = _env_int("LLM_PROVIDER_TIMEOUT_SECONDS", 90)
LLM_GEMINI_STREAM_TIMEOUT_SECONDS = _env_int("LLM_GEMINI_STREAM_TIMEOUT_SECONDS", 90)
LLM_GROK_STREAM_TIMEOUT_SECONDS = _env_int("LLM_GROK_STREAM_TIMEOUT_SECONDS", 60)
LLM_CLAUDE_STREAM_TIMEOUT_SECONDS = _env_int("LLM_CLAUDE_STREAM_TIMEOUT_SECONDS", 120)
LLM_OPENAI_STREAM_TIMEOUT_SECONDS = _env_int("LLM_OPENAI_STREAM_TIMEOUT_SECONDS", 90)
LLM_OPENAI_RESPONSES_TIMEOUT_SECONDS = _env_int("LLM_OPENAI_RESPONSES_TIMEOUT_SECONDS", 300)

# РџРµСЂРµРґ Р·Р°РїСѓСЃРєРѕРј С‚Р°СЃРєР°/РІРѕСЂРєС„Р»РѕСѓ СЃРЅР°С‡Р°Р»Р° РїСЂРѕРІРµСЂРёС‚СЊ Р·Р°РґР°С‡Сѓ С‡РµСЂРµР· Cursor (--mode=ask). Р•СЃР»Рё True вЂ” С„Р°Р·Р° В«Р°РЅР°Р»РёР·В» РїРµСЂРµРґ РІС‹РїРѕР»РЅРµРЅРёРµРј.
ANALYZE_TASK_BEFORE_RUN = os.getenv("ANALYZE_TASK_BEFORE_RUN", "1").strip().lower() in ("1", "true", "yes", "on")

# Cursor CLI: HTTP/1 mode (default on) to avoid proxy/VPN issues when HTTP/2 is blocked.
# Override: CURSOR_CLI_HTTP_1=0 or false to disable.
_raw_http1 = os.getenv("CURSOR_CLI_HTTP_1", "1").strip().lower()
CURSOR_CLI_HTTP_1 = _raw_http1 not in ("0", "false", "no", "off")


def _parse_cursor_cli_extra_env():
    """Extra env vars for Cursor CLI. When CURSOR_CLI_HTTP_1 is True, adds CURSOR_DISABLE_HTTP2=1.
    CURSOR_API_KEY (РѕС‚РґРµР»СЊРЅРѕ РІ .env) вЂ” headless-РІС…РѕРґ Р±РµР· Google; РєР»СЋС‡ РІ Cursor в†’ Settings в†’ API Access.
    Override via CURSOR_CLI_EXTRA_ENV JSON, e.g. CURSOR_CLI_EXTRA_ENV='{"KEY":"VALUE"}'."""
    raw = os.getenv("CURSOR_CLI_EXTRA_ENV", "").strip()
    if raw:
        try:
            d = json.loads(raw)
            return dict(d) if isinstance(d, dict) else {}
        except json.JSONDecodeError:
            return {}
    if CURSOR_CLI_HTTP_1:
        return {"CURSOR_DISABLE_HTTP2": "1"}
    return {}


CURSOR_CLI_EXTRA_ENV = _parse_cursor_cli_extra_env()

# Skills context composition
SKILLS_GLOBAL_RULES = os.getenv("SKILLS_GLOBAL_RULES", "").strip()
SKILLS_MAX_CONTEXT_CHARS = int(os.getenv("SKILLS_MAX_CONTEXT_CHARS", "24000"))


def _parse_path_list_env(name: str, default: list[Path]) -> list[Path]:
    raw = os.getenv(name, "").strip()
    if not raw:
        return default
    paths: list[Path] = []
    for item in raw.split(","):
        value = item.strip()
        if not value:
            continue
        paths.append(Path(value).expanduser())
    return paths or default


STUDIO_SKILLS_DIRS = _parse_path_list_env(
    "STUDIO_SKILLS_DIRS",
    [BASE_DIR / "studio" / "skills"],
)

# CLI runtime configuration for external agents
def _cli_command(env_var: str, default_name: str) -> str:
    return os.getenv(env_var) or shutil.which(default_name) or default_name


# Р”РѕСЃС‚СѓРїРЅС‹Рµ РјРѕРґРµР»Рё Cursor CLI (Р°РєС‚СѓР°Р»СЊРЅС‹Р№ СЃРїРёСЃРѕРє РїРѕ РґРѕРєСѓРјРµРЅС‚Р°С†РёРё Cursor, Р±РµР· Max Mode)
# РСЃС‚РѕС‡РЅРёРє: https://docs.cursor.com/models
CURSOR_AVAILABLE_MODELS = [
    {"id": "auto", "name": "Auto", "description": "РђРІС‚РѕРјР°С‚РёС‡РµСЃРєРёР№ РІС‹Р±РѕСЂ Р»СѓС‡С€РµР№ РјРѕРґРµР»Рё"},
    {"id": "claude-4.5-sonnet", "name": "Claude 4.5 Sonnet", "description": "РЎР±Р°Р»Р°РЅСЃРёСЂРѕРІР°РЅРЅР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "claude-4.5-opus", "name": "Claude 4.5 Opus", "description": "РЎР°РјР°СЏ РјРѕС‰РЅР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gpt-5.2", "name": "GPT-5.2", "description": "OpenAI, 272k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gpt-5.2-codex", "name": "GPT-5.2 Codex", "description": "OpenAI Codex, 272k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gemini-3-flash", "name": "Gemini 3 Flash", "description": "Google, Р±С‹СЃС‚СЂР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gemini-3-pro", "name": "Gemini 3 Pro", "description": "Google Pro, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "grok-code", "name": "Grok Code", "description": "xAI, 256k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "composer-1", "name": "Composer 1", "description": "Cursor native, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "composer-1.5", "name": "Composer 1.5", "description": "Cursor planning, 200k РєРѕРЅС‚РµРєСЃС‚"},
]

# Р РµРєРѕРјРµРЅРґР°С†РёРё РјРѕРґРµР»РµР№ РїРѕ С‚РёРїСѓ Р·Р°РґР°С‡Рё (РёСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ SmartTaskAnalyzer)
MODEL_RECOMMENDATIONS = {
    "simple": "gemini-3-flash",       # Р РµС„Р°РєС‚РѕСЂРёРЅРі, lint-fix, С„РѕСЂРјР°С‚РёСЂРѕРІР°РЅРёРµ - Р±С‹СЃС‚СЂР°СЏ РјРѕРґРµР»СЊ
    "standard": "claude-4.5-sonnet",  # РќРѕРІС‹Р№ РєРѕРґ, С„РёС‡Рё, СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рµ Р·Р°РґР°С‡Рё
    "complex": "claude-4.5-opus",     # РђСЂС…РёС‚РµРєС‚СѓСЂР°, РґРёР·Р°Р№РЅ, СЃР»РѕР¶РЅР°СЏ Р»РѕРіРёРєР°
    "debug": "gpt-5.2",               # Р”РµР±Р°Рі, Р°РЅР°Р»РёР· РѕС€РёР±РѕРє
}


CLI_RUNTIME_CONFIG = {
    "cursor": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        # --force: Р°РіРµРЅС‚ РјРѕР¶РµС‚ РјРµРЅСЏС‚СЊ С„Р°Р№Р»С‹ Р±РµР· РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ
        # --output-format stream-json: СЃС‚СЂРёРјРёРЅРі РґР»СЏ РґРµС‚Р°Р»СЊРЅС‹С… Р»РѕРіРѕРІ РїРѕ С€Р°РіР°Рј
        # --stream-partial-output: РїСЂРѕРіСЂРµСЃСЃ РїРѕ С€Р°РіР°Рј
        # РњРѕРґРµР»СЊ С‚РµРїРµСЂСЊ РїРµСЂРµРґР°С‘С‚СЃСЏ РґРёРЅР°РјРёС‡РµСЃРєРё С‡РµСЂРµР· allowed_args
        "args": ["-p", "--force", "--output-format", "stream-json", "--stream-partial-output", "--workspace", "{workspace}"],
        "prompt_style": "positional",
        # model: РІС‹Р±РѕСЂ РјРѕРґРµР»Рё (auto, gpt-5, sonnet-4, sonnet-4-thinking, opus-4)
        # sandbox: enabled|disabled, approve-mcps: bool, browser: bool
        # РќР• РґРѕР±Р°РІР»СЏРµРј allowedTools - СЌС‚Рѕ РќР• СЃС‚Р°РЅРґР°СЂС‚РЅС‹Р№ Р°СЂРіСѓРјРµРЅС‚ Cursor CLI
        "allowed_args": ["model", "sandbox", "approve-mcps", "browser"],
    },
    # cursor_server: DevOps СЂРµР¶РёРј Р‘Р•Р— --force (read-only РґР»СЏ С„Р°Р№Р»РѕРІ)
    # РСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё РґР»СЏ СЃРµСЂРІРµСЂРЅС‹С… Р·Р°РґР°С‡ (target_server_id != null)
    "cursor_server": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        # РќР•Рў --force: Р°РіРµРЅС‚ РЅРµ РјРѕР¶РµС‚ РјРµРЅСЏС‚СЊ С„Р°Р№Р»С‹ Р»РѕРєР°Р»СЊРЅРѕ
        # --sandbox enabled: РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅР°СЏ РёР·РѕР»СЏС†РёСЏ filesystem
        "args": ["-p", "--trust", "--output-format", "stream-json", "--stream-partial-output", "--workspace", "{workspace}", "--sandbox", "enabled"],
        "prompt_style": "positional",
        "allowed_args": ["model", "approve-mcps"],
    },
    # cursor_plan: режим --mode=plan для генерации workflow (Composer 1.5 пишет план)
    # Документация: https://cursor.com/docs/agent/planning
    "cursor_plan": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        "args": ["-p", "--trust", "--mode=plan", "--output-format", "text", "--workspace", "{workspace}"],
        "prompt_style": "positional",
        "allowed_args": ["model"],
    },
    "claude": {
        "command": _cli_command("CLAUDE_CLI_PATH", "claude"),
        # -p: non-interactive (programmatic) mode
        # --output-format stream-json: СЃС‚СЂРёРјРёРЅРі РґР»СЏ РґРµС‚Р°Р»СЊРЅС‹С… Р»РѕРіРѕРІ
        # --include-partial-messages: РїСЂРѕРјРµР¶СѓС‚РѕС‡РЅС‹Рµ СЃРѕРѕР±С‰РµРЅРёСЏ РїСЂРё СЃС‚СЂРёРјРёРЅРіРµ
        # --dangerously-skip-permissions: РїСЂРѕРїСѓСЃС‚РёС‚СЊ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ (РґР»СЏ headless)
        # --mcp-config: РїСѓС‚СЊ Рє JSON С„Р°Р№Р»Сѓ СЃ MCP СЃРµСЂРІРµСЂР°РјРё
        # --allowedTools: СЂР°Р·СЂРµС€С‘РЅРЅС‹Рµ РёРЅСЃС‚СЂСѓРјРµРЅС‚С‹ Р±РµР· РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ
        # --model: РІС‹Р±РѕСЂ РјРѕРґРµР»Рё claude (sonnet, opus, haiku)
        # Р”РѕРєСѓРјРµРЅС‚Р°С†РёСЏ: https://docs.anthropic.com/en/docs/claude-code
        # --debug mcp С‚СЂРµР±СѓРµС‚СЃСЏ РґР»СЏ РєРѕСЂСЂРµРєС‚РЅРѕР№ СЂР°Р±РѕС‚С‹ СЃ MCP СЃРµСЂРІРµСЂР°РјРё (Р±РµР· РЅРµРіРѕ CLI Р·Р°РІРёСЃР°РµС‚)
        "args": ["-p", "--verbose", "--output-format", "stream-json", "--include-partial-messages", "--dangerously-skip-permissions", "--debug", "mcp"],
        "prompt_style": "positional",
        "allowed_args": [
            "model",            # Р’С‹Р±РѕСЂ РјРѕРґРµР»Рё Claude
            "mcp-config",       # РџСѓС‚СЊ Рє MCP РєРѕРЅС„РёРіСѓ (РґР»СЏ server_execute Рё РґСЂ.)
            "allowedTools",     # Р Р°Р·СЂРµС€С‘РЅРЅС‹Рµ РёРЅСЃС‚СЂСѓРјРµРЅС‚С‹
            "agent",            # РљР°СЃС‚РѕРјРЅС‹Р№ Р°РіРµРЅС‚
            "continue",         # -c РґР»СЏ РїСЂРѕРґРѕР»Р¶РµРЅРёСЏ СЃРµСЃСЃРёРё
        ],
        "timeout_seconds": 1800,  # 30 РјРёРЅСѓС‚ РґР»СЏ РіР»СѓР±РѕРєРёС… РѕРїРµСЂР°С†РёР№
    },
    # Codex (OpenAI): codex exec для headless, требует CODEX_API_KEY или OPENAI_API_KEY
    # Документация: https://developers.openai.com/codex
    "codex": {
        "command": _cli_command("CODEX_CLI_PATH", "codex"),
        # --skip-git-repo-check: для пустых/новых папок (Codex по умолчанию требует git)
        "args": ["exec", "--full-auto", "--cd", "{workspace}", "--skip-git-repo-check"],
        "prompt_style": "positional",
        "allowed_args": ["model", "sandbox"],
        "timeout_seconds": 1800,
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Celery Configuration
# =============================================================================
# Redis URL for Celery broker and result backend
# Format: redis://[:password]@host:port/db_number
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Task serialization
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Timezone (use Django's timezone)
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit for graceful shutdown

# Result expiration (24 hours)
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # For long-running tasks
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "4"))

# Task routes (optional, for separating queues)
CELERY_TASK_ROUTES = {}
