from django.urls import path
from . import views

app_name = 'servers'

urlpatterns = [
    path('', views.server_list, name='server_list'),
    path('api/frontend/bootstrap/', views.frontend_bootstrap, name='frontend_bootstrap'),
    path('hub/', views.multi_terminal, name='multi_terminal'),
    path('<int:server_id>/terminal/', views.server_terminal_page, name='server_terminal'),
    path('<int:server_id>/terminal/minimal/', views.terminal_minimal, name='terminal_minimal'),
    path('api/create/', views.server_create, name='server_create'),
    path('api/<int:server_id>/update/', views.server_update, name='server_update'),
    path('api/<int:server_id>/test/', views.server_test_connection, name='server_test'),
    path('api/<int:server_id>/execute/', views.server_execute_command, name='server_execute'),
    path('api/<int:server_id>/ui/capabilities/', views.server_linux_ui_capabilities, name='server_linux_ui_capabilities'),
    path('api/<int:server_id>/ui/overview/', views.server_linux_ui_overview, name='server_linux_ui_overview'),
    path('api/<int:server_id>/ui/services/', views.server_linux_ui_services, name='server_linux_ui_services'),
    path('api/<int:server_id>/ui/services/logs/', views.server_linux_ui_service_logs, name='server_linux_ui_service_logs'),
    path('api/<int:server_id>/ui/services/action/', views.server_linux_ui_service_action, name='server_linux_ui_service_action'),
    path('api/<int:server_id>/ui/processes/', views.server_linux_ui_processes, name='server_linux_ui_processes'),
    path('api/<int:server_id>/ui/processes/action/', views.server_linux_ui_process_action, name='server_linux_ui_process_action'),
    path('api/<int:server_id>/ui/logs/', views.server_linux_ui_logs, name='server_linux_ui_logs'),
    path('api/<int:server_id>/ui/disk/', views.server_linux_ui_disk, name='server_linux_ui_disk'),
    path('api/<int:server_id>/ui/network/', views.server_linux_ui_network, name='server_linux_ui_network'),
    path('api/<int:server_id>/ui/packages/', views.server_linux_ui_packages, name='server_linux_ui_packages'),
    path('api/<int:server_id>/ui/docker/', views.server_linux_ui_docker, name='server_linux_ui_docker'),
    path('api/<int:server_id>/ui/docker/logs/', views.server_linux_ui_docker_logs, name='server_linux_ui_docker_logs'),
    path('api/<int:server_id>/ui/docker/action/', views.server_linux_ui_docker_action, name='server_linux_ui_docker_action'),
    path('api/<int:server_id>/files/', views.server_file_list, name='server_file_list'),
    path('api/<int:server_id>/files/read/', views.server_file_read_text, name='server_file_read_text'),
    path('api/<int:server_id>/files/write/', views.server_file_write_text, name='server_file_write_text'),
    path('api/<int:server_id>/files/upload/', views.server_file_upload, name='server_file_upload'),
    path('api/<int:server_id>/files/download/', views.server_file_download, name='server_file_download'),
    path('api/<int:server_id>/files/rename/', views.server_file_rename, name='server_file_rename'),
    path('api/<int:server_id>/files/delete/', views.server_file_delete, name='server_file_delete'),
    path('api/<int:server_id>/files/mkdir/', views.server_file_mkdir, name='server_file_mkdir'),
    path('api/<int:server_id>/delete/', views.server_delete, name='server_delete'),
    path('api/<int:server_id>/shares/', views.server_share_list, name='server_share_list'),
    path('api/<int:server_id>/share/', views.server_share_create, name='server_share_create'),
    path('api/<int:server_id>/shares/<int:share_id>/revoke/', views.server_share_revoke, name='server_share_revoke'),
    path('api/groups/create/', views.group_create, name='group_create'),
    path('api/groups/<int:group_id>/update/', views.group_update, name='group_update'),
    path('api/groups/<int:group_id>/delete/', views.group_delete, name='group_delete'),
    path('api/groups/<int:group_id>/add-member/', views.group_add_member, name='group_add_member'),
    path('api/groups/<int:group_id>/remove-member/', views.group_remove_member, name='group_remove_member'),
    path('api/groups/<int:group_id>/subscribe/', views.group_subscribe, name='group_subscribe'),
    path('api/bulk-update/', views.bulk_update_servers, name='bulk_update_servers'),
    path('api/global-context/', views.global_context_get, name='global_context_get'),
    path('api/global-context/save/', views.global_context_save, name='global_context_save'),
    path('api/groups/<int:group_id>/context/', views.group_context_get, name='group_context_get'),
    path('api/groups/<int:group_id>/context/save/', views.group_context_save, name='group_context_save'),
    path('api/<int:server_id>/get/', views.server_get, name='server_get'),
    path('api/<int:server_id>/reveal-password/', views.server_reveal_password, name='server_reveal_password'),
    path('api/<int:server_id>/knowledge/', views.server_knowledge_list, name='server_knowledge_list'),
    path('api/<int:server_id>/knowledge/create/', views.server_knowledge_create, name='server_knowledge_create'),
    path('api/<int:server_id>/knowledge/<int:knowledge_id>/update/', views.server_knowledge_update, name='server_knowledge_update'),
    path('api/<int:server_id>/knowledge/<int:knowledge_id>/delete/', views.server_knowledge_delete, name='server_knowledge_delete'),
    path('api/master-password/set/', views.set_master_password, name='set_master_password'),
    path('api/master-password/check/', views.get_master_password, name='get_master_password'),
    path('api/master-password/clear/', views.clear_master_password, name='clear_master_password'),

    # Monitoring
    path('api/monitoring/dashboard/', views.monitoring_dashboard, name='monitoring_dashboard'),
    path('api/<int:server_id>/health/', views.server_health_history, name='server_health_history'),
    path('api/<int:server_id>/health/check/', views.server_health_check_now, name='server_health_check_now'),
    path('api/alerts/', views.server_alerts_list, name='server_alerts_list'),
    path('api/alerts/<int:alert_id>/resolve/', views.server_alert_resolve, name='server_alert_resolve'),
    path('api/monitoring/config/', views.monitoring_config, name='monitoring_config'),
    path('api/<int:server_id>/ai-analyze/', views.ai_analyze_server, name='ai_analyze_server'),

    # Agents (mini + full)
    path('api/agents/', views.agent_list, name='agent_list'),
    path('api/agents/templates/', views.agent_templates, name='agent_templates'),
    path('api/agents/create/', views.agent_create, name='agent_create'),
    path('api/agents/<int:agent_id>/update/', views.agent_update, name='agent_update'),
    path('api/agents/<int:agent_id>/delete/', views.agent_delete, name='agent_delete'),
    path('api/agents/<int:agent_id>/run/', views.agent_run, name='agent_run'),
    path('api/agents/<int:agent_id>/stop/', views.agent_stop, name='agent_stop'),
    path('api/agents/<int:agent_id>/runs/', views.agent_runs, name='agent_runs'),
    path('api/agents/runs/<int:run_id>/', views.agent_run_detail, name='agent_run_detail'),
    path('api/agents/runs/<int:run_id>/log/', views.agent_run_log, name='agent_run_log'),
    path('api/agents/runs/<int:run_id>/reply/', views.agent_run_reply, name='agent_run_reply'),
    path('api/agents/dashboard/', views.agent_dashboard_runs, name='agent_dashboard_runs'),
    # Pipeline task editing
    path('api/agents/runs/<int:run_id>/approve-plan/', views.agent_run_approve_plan, name='agent_run_approve_plan'),
    path('api/agents/runs/<int:run_id>/tasks/<int:task_id>/update/', views.agent_run_task_update, name='agent_run_task_update'),
    path('api/agents/runs/<int:run_id>/tasks/<int:task_id>/ai-refine/', views.agent_run_task_ai_refine, name='agent_run_task_ai_refine'),
]
