# Generated by Codex on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0002_pipelinetrigger_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="skill_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of attached skill slugs, e.g. ["keycloak-safety", "keycloak-prod-profile"]',
            ),
        ),
    ]
