# Generated by Django 5.2.10 on 2026-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servergroup_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='behind_firewall',
            field=models.BooleanField(default=True, help_text='Сервер за корпоративным файрволлом'),
        ),
        migrations.AddField(
            model_name='server',
            name='has_proxy',
            field=models.BooleanField(default=False, help_text='Сервер работает через прокси'),
        ),
        migrations.AddField(
            model_name='server',
            name='network_config',
            field=models.JSONField(blank=True, default=dict, help_text='Контекст корпоративной сети: прокси, VPN, firewall, env variables'),
        ),
        migrations.AddField(
            model_name='server',
            name='requires_vpn',
            field=models.BooleanField(default=False, help_text='Требуется VPN для подключения'),
        ),
    ]
