# Generated by Django 5.2.10 on 2026-02-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_knowledge_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalserverrules',
            options={'verbose_name': 'Global Server Rules', 'verbose_name_plural': 'Global Server Rules'},
        ),
        migrations.RenameIndex(
            model_name='serverknowledge',
            new_name='servers_ser_server__adf384_idx',
            old_name='srv_knowledge_idx',
        ),
    ]
