# Generated by Django 5.2.10 on 2026-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_add_projects_sprints_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ssh', 'SSH (Linux)'), ('rdp', 'RDP (Windows)')], default='ssh', help_text='SSH для Linux, RDP для Windows', max_length=10),
        ),
    ]
