# Generated by Django 5.2.10 on 2026-02-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servers", "0007_add_server_type_rdp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("share_context", models.BooleanField(default=True, help_text="Передавать ли AI-контекст сервера (corporate/network/group/global rules) пользователю с доступом")),
                ("expires_at", models.DateTimeField(blank=True, help_text="Если задано, доступ автоматически истекает в это время", null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("server", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="servers.server")),
                ("shared_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="server_shares_sent", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="server_shares", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("server", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="servershare",
            index=models.Index(fields=["user", "is_revoked"], name="servers_ser_user_id_50190e_idx"),
        ),
        migrations.AddIndex(
            model_name="servershare",
            index=models.Index(fields=["server", "is_revoked"], name="servers_ser_server__2437bc_idx"),
        ),
        migrations.AddIndex(
            model_name="servershare",
            index=models.Index(fields=["expires_at"], name="servers_ser_expires_8272af_idx"),
        ),
    ]
