# Generated by Django 5.2.10 on 2026-03-02 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_server_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('cpu', 'High CPU'), ('memory', 'High Memory'), ('disk', 'High Disk'), ('service', 'Failed Service'), ('log_error', 'Log Error'), ('unreachable', 'Unreachable')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unreachable', 'Unreachable')], default='healthy', max_length=20)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('memory_used_mb', models.IntegerField(blank=True, null=True)),
                ('memory_total_mb', models.IntegerField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('disk_used_gb', models.FloatField(blank=True, null=True)),
                ('disk_total_gb', models.FloatField(blank=True, null=True)),
                ('load_1m', models.FloatField(blank=True, null=True)),
                ('load_5m', models.FloatField(blank=True, null=True)),
                ('load_15m', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_deep', models.BooleanField(default=False)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='servershare',
            new_name='servers_ser_user_id_dbcf29_idx',
            old_name='servers_ser_user_id_50190e_idx',
        ),
        migrations.RenameIndex(
            model_name='servershare',
            new_name='servers_ser_server__e416ca_idx',
            old_name='servers_ser_server__2437bc_idx',
        ),
        migrations.RenameIndex(
            model_name='servershare',
            new_name='servers_ser_expires_3ee885_idx',
            old_name='servers_ser_expires_8272af_idx',
        ),
        migrations.AddField(
            model_name='serveralert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serveralert',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='servers.server'),
        ),
        migrations.AddField(
            model_name='serverhealthcheck',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='servers.server'),
        ),
        migrations.AddIndex(
            model_name='serveralert',
            index=models.Index(fields=['server', '-created_at'], name='servers_ser_server__77ad67_idx'),
        ),
        migrations.AddIndex(
            model_name='serveralert',
            index=models.Index(fields=['is_resolved', '-created_at'], name='servers_ser_is_reso_187753_idx'),
        ),
        migrations.AddIndex(
            model_name='serveralert',
            index=models.Index(fields=['severity', '-created_at'], name='servers_ser_severit_ccb97d_idx'),
        ),
        migrations.AddIndex(
            model_name='serverhealthcheck',
            index=models.Index(fields=['server', '-checked_at'], name='servers_ser_server__c37195_idx'),
        ),
        migrations.AddIndex(
            model_name='serverhealthcheck',
            index=models.Index(fields=['status', '-checked_at'], name='servers_ser_status_2a1d1b_idx'),
        ),
    ]
