# Generated by Django 5.2.10 on 2026-03-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_add_health_check_and_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agent_type', models.CharField(choices=[('security_audit', 'Security Audit'), ('log_analyzer', 'Log Analyzer'), ('performance', 'Performance Profile'), ('disk_report', 'Disk Report'), ('docker_status', 'Docker Status'), ('service_health', 'Service Health'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('commands', models.JSONField(default=list, help_text='List of shell commands to execute')),
                ('ai_prompt', models.TextField(blank=True, help_text='Extra instruction for AI analysis')),
                ('schedule_minutes', models.IntegerField(default=0, help_text='0 = manual only')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servers', models.ManyToManyField(blank=True, related_name='agents', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('commands_output', models.JSONField(default=list, help_text='[{cmd, stdout, stderr, exit_code, duration_ms}]')),
                ('ai_analysis', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='servers.server')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='servers.serveragent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serveragent',
            index=models.Index(fields=['user', '-updated_at'], name='servers_ser_user_id_8af600_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent', '-started_at'], name='servers_age_agent_i_dd9b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['server', '-started_at'], name='servers_age_server__37a709_idx'),
        ),
    ]
