# Generated by Django 5.2.10 on 2026-03-02 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_add_server_agent_and_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='connected_servers',
            field=models.JSONField(blank=True, default=list, help_text='[{server_id, server_name, connected_at}]'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='final_report',
            field=models.TextField(blank=True, help_text='Final structured report from full agent'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='iterations_log',
            field=models.JSONField(blank=True, default=list, help_text='[{iteration, thought, action, tool, args, observation, timestamp}]'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='pending_question',
            field=models.TextField(blank=True, help_text='Question agent is waiting user to answer'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list, help_text='[{tool, args, result, duration_ms, timestamp}]'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='total_iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='allow_multi_server',
            field=models.BooleanField(default=False, help_text='Allow simultaneous multi-server connections'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='goal',
            field=models.TextField(blank=True, help_text='Goal for the agent to achieve (full mode)'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='max_connections',
            field=models.IntegerField(default=5, help_text='Max simultaneous SSH connections'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='max_iterations',
            field=models.IntegerField(default=20, help_text='Max ReAct loop iterations (1-100)'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='mode',
            field=models.CharField(choices=[('mini', 'Mini Agent'), ('full', 'Full Agent (ReAct)')], default='mini', max_length=10),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='session_timeout_seconds',
            field=models.IntegerField(default=600, help_text='Max session duration in seconds'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='stop_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Conditions to stop the agent early'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='System prompt defining agent role and style'),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='tools_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tool availability overrides'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting for user'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='agent_type',
            field=models.CharField(choices=[('security_audit', 'Security Audit'), ('log_analyzer', 'Log Analyzer'), ('performance', 'Performance Profile'), ('disk_report', 'Disk Report'), ('docker_status', 'Docker Status'), ('service_health', 'Service Health'), ('custom', 'Custom'), ('security_patrol', 'Security Patrol'), ('deploy_watcher', 'Deploy Watcher'), ('log_investigator', 'Log Investigator'), ('infra_scout', 'Infrastructure Scout'), ('multi_health', 'Multi-Server Health')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='commands',
            field=models.JSONField(default=list, help_text='List of shell commands (mini mode)'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-started_at'], name='servers_age_status_01c5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='serveragent',
            index=models.Index(fields=['user', 'mode'], name='servers_ser_user_id_74da05_idx'),
        ),
    ]
