# Generated by Django 5.2.10 on 2026-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_full_agents_extend_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='orchestrator_log',
            field=models.JSONField(blank=True, default=list, help_text='[{role, content, timestamp}] — orchestrator LLM conversation history'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='plan_tasks',
            field=models.JSONField(blank=True, default=list, help_text='[{id, name, description, status, thought, action, args, result, error, iterations, orchestrator_decision, started_at, completed_at}]'),
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='mode',
            field=models.CharField(choices=[('mini', 'Mini Agent'), ('full', 'Full Agent (ReAct)'), ('multi', 'Multi-Agent Pipeline')], default='mini', max_length=10),
        ),
    ]
