# Generated by Django 5.2.10 on 2026-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_agent_multi_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting for user'), ('plan_review', 'Awaiting Plan Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=20),
        ),
    ]
