# Generated by Django 5.2.10 on 2026-03-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_add_plan_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='servers.serveragent'),
        ),
    ]
