# Generated by Django 5.2.10 on 2026-03-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_agentrun_agent_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='servers.server'),
        ),
    ]
