# Generated by Django 5.2.10 on 2026-01-27 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('agents', 'Agents'), ('orchestrator', 'Orchestrator'), ('servers', 'Servers'), ('tasks', 'Tasks'), ('knowledge_base', 'Knowledge Base'), ('settings', 'Settings')], max_length=30)),
                ('allowed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'feature'],
                'indexes': [models.Index(fields=['user', 'feature'], name='core_ui_use_user_id_036f2b_idx')],
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
