# Generated by Django 6.0.1 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0002_chat_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapppermission",
            name="feature",
            field=models.CharField(
                choices=[
                    ("agents", "Agents"),
                    ("orchestrator", "Orchestrator"),
                    ("servers", "Servers"),
                    ("tasks", "Tasks"),
                    ("knowledge_base", "Knowledge Base"),
                    ("passwords", "Passwords"),
                    ("settings", "Settings"),
                ],
                max_length=30,
            ),
        ),
    ]
