# Generated by Django 5.2.6 on 2026-02-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0003_userapppermission_add_passwords_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(default='other', max_length=40)),
                ('action', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(blank=True, default='', max_length=40)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['-created_at'], name='core_ui_use_created_5b0ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='core_ui_use_user_id_770762_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['category', '-created_at'], name='core_ui_use_categor_ed9814_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', '-created_at'], name='core_ui_use_action_40bc15_idx'),
        ),
    ]
